import Head from 'next/head'
import { useEffect } from 'react';
import { useState } from 'react';
import getAllQuestion from '../libs/getAllQuestion';
import restartQuiz from '../libs/restartQuiz';
import startQuiz from '../libs/startQuiz';
import submitAnswer from '../libs/submitAnswer';

export default function Home() {
  const [start,setStart] = useState(false)
  const [result,setResult] = useState(false)
  const [questions,setQuestions] = useState([])
  const [currentQuestion,setCurrentQuestion] = useState(0)
  const [name,setName] = useState('')
  const [score,setScore] = useState(0)
  useEffect(()=>{
    getAllQuestion(setQuestions)
  },[])
  console.log(questions)
  return (
    <div className=''>
      <Head>
        <title>ইসলামিক কুইজ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='index'>
        {!start && <div className="start">
          <div className="">
            <input type="text" placeholder='আপনার নাম লিখুন' onChange={(e)=>setName(e.target.value)} required/>
            <br />
            <button onClick={() => startQuiz(name,setStart)}>বিসমিল্লাহ্‌</button>
          </div>
        </div>}
        {start && !result && <div className="qustion_answer">
          <div className="question">
            <h1>
              <span className='text-2xl pr-4'>Question</span>
              <span className='text-2xl'>{currentQuestion}</span>/
              <span>{questions.length}</span>
            </h1>
            <p>{questions[currentQuestion]?.question}</p>
          </div>
          <div className="answer">
            <p className="text-center text-xl">আপনার উত্তর টি খুজুনঃ</p>
            {
              questions[currentQuestion].answers.map((answer,i)=><button key={i} onClick={()=>submitAnswer(answer.isCorrect,questions,currentQuestion,setCurrentQuestion,setResult,score,setScore)}>{answer.answer}</button>)
            }
          </div>
        </div>}
        {result && <div className="result">
            <div className="">
              <span>{score > 0 ? 'আলহামদুলিল্লাহ ' : ' আলহামদুলিল্লাহ শুভ কামনা '} {name}</span>
              <br />
              <span> আপনার স্কোর হল :  {score}</span>
              <br />
              {score === 0 && <span>পরবর্তীতে আরো ভাল করবেন ইনশাল্লাহ ।</span>}
              <br />
              <button onClick={()=>restartQuiz(setName,setStart,setResult,setCurrentQuestion)}>আবার শুরু করুন</button>
            </div>
        </div>}
      </div>
    </div>
  )
}
